app/users/views.py
from flask import render_template, flash, redirect, session, url_for, request, g, jsonify, Blueprint
from flask.ext.login import login_user, logout_user, current_user, login_required
from app import app, oid, db, login_manager
from app.users.forms import LoginForm
from datetime import datetime
from app.users.models import User, ROLE_USER, ROLE_ADMIN
from app.main_app.models import UserDetails
from app.decorators import crossdomain


users = Blueprint('users', __name__)

@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

@app.before_request
def before_request():
    g.user = current_user
    if g.user.is_authenticated():
        g.user.last_seen = datetime.utcnow()
        db.session.add(g.user)
        db.session.commit()
        g.login_form = LoginForm()
        #g.search_form = SearchForm()
 
@oid.after_login
def after_login(resp):
    if resp.email is None or resp.email == "":
        flash(gettext('Invalid login. Please try again.'))
        return redirect(url_for('login_view'))
    user = User.query.filter_by(email = resp.email).first()
    userdetails = UserDetails(user=user)
    if user is None:
        nickname = resp.nickname
        if nickname is None or nickname == "":
            nickname = resp.email.split('@')[0]
        nickname = User.make_valid_nickname(nickname)
        nickname = User.make_unique_nickname(nickname)
        user = User(nickname = nickname, email = resp.email, role = ROLE_USER)
        
        db.session.add(user)
        db.session.add(userdetails)
        db.session.commit()
        # make the user follow him/herself
        db.session.add(user.follow(user))
        db.session.commit()
        
    userdetails = UserDetails.query.filter_by(user=user).first()
    if userdetails is None:
        userdetails = UserDetails(user=user)
        db.session.add(userdetails)
        db.session.commit()
        
    remember_me = False
    if 'remember_me' in session:
        remember_me = session['remember_me']
        session.pop('remember_me', None)
    login_user(user, remember = True)
    return redirect(request.args.get('next') or url_for('main_flow.index'))


@users.route('/login', methods = ['GET', 'POST'])
@oid.loginhandler
def login_view():
    if g.user is not None and g.user.is_authenticated():
        return redirect(url_for('main_flow.index'))
    form = LoginForm()
    openid = request.form.get('openid',None)
    if form.validate_on_submit():
        print "logging"
        session['remember_me'] = form.remember_me.data
        return oid.try_login(form.openid.data, ask_for = ['nickname', 'email','country','fullname','dob'])
    
    return render_template('login.html', 
        title = 'Sign In',
        form = form,
        providers = app.config['OPENID_PROVIDERS'])


@users.route('/profile/<nickname>', methods = ['GET', 'POST'])
def user_profile(nickname=None):
    if nickname is None:
        user = g.user
    else:
        user = User.query.filter_by(nickname=nickname).first()
    if user and user.is_authenticated():
        return render_template('user_profile.html',user=user)
    flash("The userprofile is not existing.")
    return render_template('user_profile.html')


@users.route('/ajax_login', methods = ['GET', 'POST'])  
def ajax_login():
    print "Ajax request", request.form.get('openid',None),request.form.get('provider',None)
    return jsonify({'d':1})

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main_flow.index'))

app/templates/base.html
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
<link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" />
<title>Connection : It is game for your brain</title>
<!-- Bootstrap -->
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
<!--<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,700,600' rel='stylesheet' type='text/css'>-->
<!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
<link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" type="text/css">
<script src="{{ url_for('static',filename='js/jquery-2.1.0.min.js') }}"></script>
</head>


<body>
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="../" class="navbar-brand">Connection!!</a>
          <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="{{ url_for('main_flow.index') }}" id="home">Home</a>
              
            </li>
           
          </ul>

          <ul class="nav navbar-nav navbar-right">
	   {% if g.user.is_authenticated() %}
		<li><a href="{{ url_for('users.user_profile',nickname=g.user.nickname) }}">Hai {{g.user.nickname}}!!</a></li>
	   	<li><a href="{{ url_for('users.logout') }}">Logout</a></li>
	   {% else %}
		<li><a href="{{ url_for('users.login_view') }}">Login</a></li>
	   {% endif %}
            <li><a href="/about.html" target="_blank">About</a></li>
            
          </ul>

        </div>
      </div>
    </div>

<div class="container">
	<div class="page-header" id="banner">
        <div class="row">
          <div class="col-lg-6">
            <h1>Commonify</h1>
          </div>
	</div>
	{% block flashes %}
	{% include 'flash.html' %}
	{% endblock flashes %}
	{% block content %}
	{% endblock content %}
	
	</div>
</div>

{% block extrajs %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{{ url_for('static',filename='js/bootstrap.min.js') }}"></script>
    <script>
		$('.carousel').carousel()
	</script>
{% endblock extrajs %}

</body>
</html>

app/templates/flash.html
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages|unique %}
<div class="alert alert-info">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
{% from "post.html" import post %}

<div class="body">

<h3>Welcome you to connection home page</h3>
<div class="row">
{% for ic in posts.items %}
    <div><h2>{{page}}/{{total}}</h2></div>
    {{ post(ic) }}
{% endfor %}

<ul class="pager">
    {% if posts.has_next %}
    <li class="next"><a href="{{ url_for('main_flow.index', page = posts.next_num) }}">Next Tip</a></li>
    {% endif %}
</ul>
</div>

<form name="ans" method="post">
Ans: <input type="text" size=40 id="answering" name="answering">

</form>

</div>

{% endblock content %}

app/templates/login.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}

<script type="text/javascript">

function set_openid(openid, pr)
{
    u = openid.search('<username>');
    if (u != -1) {
        // openid requires username
        user = prompt('Enter your ' + pr + ' username:');
        openid = openid.substr(0, u) + user;
    }
    form = document.forms['login'];
    form.elements['openid'].value = openid;
    form.submit();
}

function ajax_login(openid, provider) {
   
	u = openid.search('<username>');
    if (u != -1) {
        // openid requires username
        user = prompt('Enter your ' + pr + ' username:');
        openid = openid.substr(0, u) + user;
    }

	//form = document.forms['login'];
    //form.elements['openid'].value = openid;

    var request = $.post('/login', {
        openid: openid,
		provider: provider
    });
	request.done(function(result) {
        	alert('success!!');
   	 });
	request.fail(function() {
        	alert('Fail!!');
    	});
}

$(document).ready(function() {
	
  $("#async_login").click(function() {
	alert('clicked!!');
	ajax_login('Google','Google');
	});
});

</script>

{% include "flash.html" %}

<div class="well">
    <h3>{{ 'Sign In' }}</h3>

       <form class="form" action="" method="post" name="login">
        {{form.hidden_tag()}}
        <!--<div class="help-block">{{ 'Click on your OpenID provider below:' }}</div> -->
        <div class="control-group">
            {% for pr in providers %}
            <a href="javascript:set_openid('{{pr.url}}', '{{pr.name}}');"><img src="/static/images/{{pr.name.lower()}}.png" class="img-polaroid" style="margin:2px; height:45px; width:auto;" /></a>
            {% endfor %}
        </div>
        <div class="control-group{% if form.errors.openid %} error{% endif %}" style="display:none;">
            <label class="control-label" for="openid">{{ 'Or enter your OpenID here:' }}</label>
            <div class="controls">
                {{ form.openid(size = 80, class = "span4") }}
                {% for error in form.errors.openid %}
                    <span class="help-inline">[{{error}}]</span><br>
                {% endfor %}
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox" for="remember_me">
                    {{ form.remember_me }} {{ 'Remember Me' }}
                </label>
            </div>
        </div>
        <div class="control-group" style="display:none;">
            <div class="controls">
                <input class="btn btn-primary" type="submit" value="{{'Sign In' }}">
            </div>
        </div>
    </form> 

</div>
{% endblock %}

app/templates/post.html
{% macro post(ic, size=20) -%}
	<div class="post">
		<div class="pimg">
		<img id="post{{ic.id}}" src="/static/play_files/{{ic.path}}">
		</div>
		<div class="hint">
			<h2 style="background-color:yellow;display: inline;">{{ic.hint}}</h2>
		</div>
	</div>

    
{%- endmacro %}

app/templates/user_profile.html
{% extends "base.html" %}

{% block flashes %}{% endblock %}
{% block content %}
{% if user %}
	<h1>Hi {{user.nickname}}!!</h1>
{% else %}
	<span>profile Not found </span>
{% endif %}
{% endblock %}